name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'

  pull_request:
    branches:
      - main
    paths:
      - 'main.tf'

  workflow_dispatch:

jobs:
  lint:
    name: Run Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check 
      
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Validate Terraform
      run: terraform validate 
